package com.enicarthage.incubator.model;

public enum ApplicationStatus {
    PENDING, REJECTED, COMPLETED,
    ACCEPTED_ROUND_1, ACCEPTED_ROUND_2, ACCEPTED_ROUND_3, ACCEPTED_ROUND_4, ACCEPTED_ROUND_5,
    ELIMINATED_ROUND_1, ELIMINATED_ROUND_2, ELIMINATED_ROUND_3, ELIMINATED_ROUND_4, ELIMINATED_ROUND_5
}
